const Icons = {
    "Accept Medium": "\uf78c",
    Accept: "\ue8fb",
    "Accident Solid": "\uea8e",
    Accident: "\ue81f",
    Accounts: "\ue910",
    "Action Center Asterisk": "\uea21",
    "Action Center Mirrored": "\ued0d",
    "Action Center Notification Mirrored": "\ued0c",
    "Action Center Notification": "\ue7e7",
    "Action Center Quiet Notification": "\uee7a",
    "Action Center Quiet": "\uee79",
    "Action Center": "\ue91c",
    "Add Bold": "\uf8aa",
    "Add Friend": "\ue8fa",
    "Add New Line Fill": "\uf7b8",
    "Add New Line": "\uf7b7",
    "Add Remote Device": "\ue836",
    "Add Surface Hub": "\uecc4",
    "Add To": "\uecc8",
    Add: "\ue710",
    "Adjust Hologram": "\uebd2",
    Admin: "\ue7ef",
    "Airplane Solid": "\ueb4c",
    Airplane: "\ue709",
    "Align Center": "\ue8e3",
    "Align Left": "\ue8e4",
    "Align Right": "\ue8e2",
    "All Apps Mirrored": "\uea40",
    "All Apps": "\ue71d",
    Annotation: "\ue924",
    "App Icon Default Add": "\uefda",
    "App Icon Default": "\uecaa",
    "Application Guard": "\uf0ef",
    Apps: "\ued35",
    "Area Chart": "\ue9d2",
    "Arrow Down 8": "\uf0ae",
    "Arrow Left 8": "\uf0b0",
    "Arrow Right 8": "\uf0af",
    "Arrow Up 8": "\uf0ad",
    "Aspect Ratio": "\ue799",
    "Asterisk Badge 12": "\uedad",
    Asterisk: "\uea38",
    "Attach Camera": "\ue8a2",
    Attach: "\ue723",
    Audio: "\ue8d6",
    "Back Mirrored": "\uf0d2",
    "Back Solid Bold": "\uf8ac",
    "Back Space QWERTY Lg": "\ueb96",
    "Back Space QWERTY Md": "\ue926",
    "Back Space QWERTY Sm": "\ue925",
    "Back Space QWERTY": "\ue750",
    "Back To Window": "\ue73f",
    Back: "\ue72b",
    "Background Toggle": "\uef1f",
    Badge: "\uec1b",
    "Band Battery 0": "\uecb9",
    "Band Battery 1": "\uecba",
    "Band Battery 2": "\uecbb",
    "Band Battery 3": "\uecbc",
    "Band Battery 4": "\uecbd",
    "Band Battery 5": "\uecbe",
    "Band Battery 6": "\uecbf",
    Bank: "\ue825",
    "Barcode Scanner": "\uec5a",
    "Battery 0": "\ue850",
    "Battery 1": "\ue851",
    "Battery 10": "\ue83f",
    "Battery 2": "\ue852",
    "Battery 3": "\ue853",
    "Battery 4": "\ue854",
    "Battery 5": "\ue855",
    "Battery 6": "\ue856",
    "Battery 7": "\ue857",
    "Battery 8": "\ue858",
    "Battery 9": "\ue859",
    "Battery Charging 0": "\ue85a",
    "Battery Charging 1": "\ue85b",
    "Battery Charging 10": "\uea93",
    "Battery Charging 2": "\ue85c",
    "Battery Charging 3": "\ue85d",
    "Battery Charging 4": "\ue85e",
    "Battery Charging 5": "\ue85f",
    "Battery Charging 6": "\ue860",
    "Battery Charging 7": "\ue861",
    "Battery Charging 8": "\ue862",
    "Battery Charging 9": "\ue83e",
    "Battery Saver 0": "\ue863",
    "Battery Saver 1": "\ue864",
    "Battery Saver 10": "\uea95",
    "Battery Saver 2": "\ue865",
    "Battery Saver 3": "\ue866",
    "Battery Saver 4": "\ue867",
    "Battery Saver 5": "\ue868",
    "Battery Saver 6": "\ue869",
    "Battery Saver 7": "\ue86a",
    "Battery Saver 8": "\ue86b",
    "Battery Saver 9": "\uea94",
    "Battery Unknown": "\ue996",
    Beaker: "\uf196",
    Beta: "\uea24",
    "Bidi Ltr": "\ue9aa",
    "Bidi Rtl": "\ue9ab",
    "Block Contact": "\ue8f8",
    "Blocked 2": "\uece4",
    Blocked: "\ue733",
    "Blue Light": "\uf08c",
    Bluetooth: "\ue702",
    "Body Cam": "\uec80",
    Bold: "\ue8dd",
    "Bookmarks Mirrored": "\uea41",
    Bookmarks: "\ue8a4",
    Brightness: "\ue706",
    Broom: "\uea99",
    "Browse Photos": "\ue7c5",
    "Brush Size": "\ueda8",
    Bug: "\uebe8",
    "Building Energy": "\uec0b",
    Bull: "\uec83",
    "Bulleted List 2 Mirrored": "\uf2c8",
    "Bulleted List 2": "\uf2c7",
    "Bulleted List Mirrored": "\uea42",
    "Bulleted List": "\ue8fd",
    Bullseye: "\uf272",
    "Bumper Left": "\uf10c",
    "Bumper Right": "\uf10d",
    "Bus Solid": "\ueb47",
    Bus: "\ue806",
    "Button A": "\uf093",
    "Button B": "\uf094",
    "Button Menu": "\uede3",
    "Button View 2": "\ueeca",
    "Button X": "\uf096",
    "Button Y": "\uf095",
    Cafe: "\uec32",
    "Calculator Addition": "\ue948",
    "Calculator Backspace": "\ue94f",
    "Calculator Divide": "\ue94a",
    "Calculator Equal To": "\ue94e",
    "Calculator Multiply": "\ue947",
    "Calculator Negate": "\ue94d",
    "Calculator Percentage": "\ue94c",
    "Calculator Squareroot": "\ue94b",
    "Calculator Subtract": "\ue949",
    Calculator: "\ue8ef",
    "Calendar Day": "\ue8bf",
    "Calendar Mirrored": "\ued28",
    "Calendar Reply": "\ue8f5",
    "Calendar Solid": "\uea89",
    Calendar: "\ue787",
    "Calendar Week": "\ue8c0",
    "Call Control": "\ue80b",
    "Call Forward International Mirrored": "\uea43",
    "Call Forward International": "\ue87a",
    "Call Forward Roaming Mirrored": "\uea44",
    "Call Forward Roaming": "\ue87b",
    "Call Forwarding Mirrored": "\uea97",
    "Call Forwarding": "\ue7f2",
    "Calligraphy Fill": "\uf0c7",
    "Calligraphy Pen": "\uedfb",
    Calories: "\uecad",
    "Camera Off": "\ue678",
    Camera: "\ue722",
    "Cancel Medium": "\uf78a",
    Cancel: "\ue711",
    Caption: "\ue8ba",
    Car: "\ue804",
    "Caret Bottom Right Solid Center 8": "\uf169",
    "Caret Down 8": "\uedd8",
    "Caret Down Solid 8": "\ueddc",
    "Caret Left 8": "\uedd5",
    "Caret Left Solid 8": "\uedd9",
    "Caret Right 8": "\uedd6",
    "Caret Right Solid 8": "\uedda",
    "Caret Solid Down": "\uf08e",
    "Caret Solid Left": "\uf08d",
    "Caret Solid Right": "\uf08f",
    "Caret Solid Up": "\uf090",
    "Caret Up 8": "\uedd7",
    "Caret Up Solid 8": "\ueddb",
    "Cash Drawer": "\uec59",
    CC: "\ue7f0",
    "Cell Phone": "\ue8ea",
    Certificate: "\ueb95",
    "Character Appearance": "\uf17f",
    Characters: "\ue8c1",
    "Chat Bubbles": "\ue8f2",
    "Check List": "\ue9d5",
    "Check Mark": "\ue73e",
    "Checkbox 14": "\uf16b",
    "Checkbox Composite 14": "\uf16c",
    "Checkbox Composite Reversed": "\ue73d",
    "Checkbox Composite": "\ue73a",
    "Checkbox Fill": "\ue73b",
    "Checkbox Indeterminate Combo 14": "\uf16d",
    "Checkbox Indeterminate Combo": "\uf16e",
    "Checkbox Indeterminate": "\ue73c",
    Checkbox: "\ue739",
    "Checklist Mirrored": "\uf0b5",
    Cherries: "\ueaa3",
    "Cheveron Left 20": "\uf743",
    "Cheveron Left 32": "\uf744",
    "Cheveron Right 20": "\uf745",
    "Cheveron Right 32": "\uf746",
    "Chevron Down Med": "\ue972",
    "Chevron Down Small": "\ue96e",
    "Chevron Down": "\ue70d",
    "Chevron Left Med": "\ue973",
    "Chevron Left Small": "\ue96f",
    "Chevron Left": "\ue76b",
    "Chevron Right Med": "\ue974",
    "Chevron Right Small": "\ue970",
    "Chevron Right": "\ue76c",
    "Chevron Up Med": "\ue971",
    "Chevron Up Small": "\ue96d",
    "Chevron Up": "\ue70e",
    "Chinese Bo Po Mo Fo": "\ue989",
    "Chinese Changjie": "\ue981",
    "Chinese Pinyin": "\ue98a",
    "Chinese Punctuation": "\uf111",
    "Chinese Quick": "\ue984",
    "Chip Card Credit Card Reader": "\uef40",
    "Chrome Annotate Contrast": "\uf0f9",
    "Chrome Annotate": "\ue931",
    "Chrome Back Contrast Mirrored": "\uf0d6",
    "Chrome Back Contrast": "\uf0d5",
    "Chrome Back Mirrored": "\uea47",
    "Chrome Back To Window Contrast": "\uf0d7",
    "Chrome Back To Window": "\ue92c",
    "Chrome Back": "\ue830",
    "Chrome Close Contrast": "\uef2c",
    "Chrome Close": "\ue8bb",
    "Chrome Full Screen Contrast": "\uf0d8",
    "Chrome Full Screen": "\ue92d",
    "Chrome Maximize Contrast": "\uef2e",
    "Chrome Maximize": "\ue922",
    "Chrome Minimize Contrast": "\uef2d",
    "Chrome Minimize": "\ue921",
    "Chrome Restore Contrast": "\uef2f",
    "Chrome Restore": "\ue923",
    "Chrome Switch Contast": "\uf1cc",
    "Chrome Switch": "\uf1cb",
    "CHT Language Bar": "\uf69e",
    "Circle Fill Badge 12": "\uedb0",
    "Circle Fill": "\uea3b",
    "Circle Pause": "\uf2d9",
    "Circle Ring Badge 12": "\uedaf",
    "Circle Ring": "\uea3a",
    "Circle Shape Solid": "\uf63c",
    "City Next 2": "\uec07",
    "City Next": "\uec06",
    "Clear All Ink Mirrored": "\uef19",
    "Clear All Ink": "\ued62",
    "Clear Selection Mirrored": "\uea48",
    "Clear Selection": "\ue8e6",
    Clear: "\ue894",
    "Click Solid": "\uf8af",
    Click: "\ue8b0",
    "Clicked Out Loud Solid Bold": "\uf8b3",
    "Clipboard List Mirrored": "\uf0e4",
    "Clipboard List": "\uf0e3",
    "Clipping Tool": "\uf406",
    "Close Pane Mirrored": "\uea49",
    "Close Pane": "\ue89f",
    "Cloud Download": "\uebd3",
    "Cloud Not Synced": "\uec9c",
    "Cloud Printer": "\ueda6",
    "Cloud Search": "\uede4",
    Cloud: "\ue753",
    Code: "\ue943",
    "Collapse Content Single": "\uf166",
    "Collapse Content": "\uf165",
    "Collate Landscape Separated": "\uf5ac",
    "Collate Landscape": "\uf57b",
    "Collate Portrait Separated": "\uf57d",
    "Collate Portrait": "\uf57c",
    "Color Off": "\uf570",
    "Color Solid": "\uf354",
    Color: "\ue790",
    "Comma Key": "\ue9ad",
    "Command Prompt": "\ue756",
    Comment: "\ue90a",
    Communications: "\ue95a",
    "Companion App": "\uec64",
    "Companion Device Framework": "\ued5d",
    "Completed Solid": "\uec61",
    Completed: "\ue930",
    Component: "\ue950",
    "Compose Mode": "\uf6a9",
    "Connect App": "\ued5c",
    Connect: "\ue703",
    Connected: "\uf0b9",
    "Construction Cone": "\ue98f",
    "Construction Solid": "\uea8d",
    Construction: "\ue822",
    "Contact 2": "\ue8d4",
    "Contact Info Mirrored": "\uea4a",
    "Contact Info": "\ue779",
    "Contact Presence": "\ue8cf",
    "Contact Solid": "\uea8c",
    Contact: "\ue77b",
    Contrast: "\ue7a1",
    "Copy Path": "\ue62f",
    "Copy To": "\uf413",
    Copy: "\ue8c8",
    Courthouse: "\uec08",
    Crop: "\ue7a8",
    "Ctrl Spatial Left": "\uf3e7",
    "Ctrl Spatial Right": "\uf11b",
    Cut: "\ue8c6",
    Cycling: "\ueac7",
    "Dash Key": "\ue9ae",
    "Data Sense Bar": "\ue7a5",
    "Data Sense": "\ue791",
    "Date Time Mirrored": "\uee93",
    "Date Time": "\uec92",
    "Decline Call": "\uf405",
    "Default APN": "\uf080",
    "Defender App": "\ue83d",
    "Defender Badge 12": "\uf0fb",
    "Delete Lines Fill": "\uf7b0",
    "Delete Lines": "\uf7af",
    Delete: "\ue74d",
    "Delete Word Fill": "\uf7ae",
    "Delete Word": "\uf7ad",
    "Delivery Optimization": "\uf785",
    Design: "\ueb3c",
    "Detachable PC": "\uf103",
    "Dev Update": "\uecc5",
    "Developer Tools": "\uec7a",
    "Device Discovery": "\uebde",
    "Device Laptop No Pic": "\ue7f8",
    "Device Laptop Pic": "\ue7f7",
    "Device Monitor Left Pic": "\ue7fa",
    "Device Monitor No Pic": "\ue7fb",
    "Device Monitor Right Pic": "\ue7f9",
    "Devices 2": "\ue975",
    "Devices 3": "\uea6c",
    "Devices 4": "\ueb66",
    Devices: "\ue772",
    Diagnostic: "\ue9d9",
    "Dial 1": "\uf146",
    "Dial 10": "\uf14f",
    "Dial 11": "\uf150",
    "Dial 12": "\uf151",
    "Dial 13": "\uf152",
    "Dial 14": "\uf153",
    "Dial 15": "\uf154",
    "Dial 16": "\uf155",
    "Dial 2": "\uf147",
    "Dial 3": "\uf148",
    "Dial 4": "\uf149",
    "Dial 5": "\uf14a",
    "Dial 6": "\uf14b",
    "Dial 7": "\uf14c",
    "Dial 8": "\uf14d",
    "Dial 9": "\uf14e",
    "Dial Shape 1": "\uf156",
    "Dial Shape 2": "\uf157",
    "Dial Shape 3": "\uf158",
    "Dial Shape 4": "\uf159",
    "Dial Up": "\ue83c",
    Dialpad: "\ue75f",
    "Dictionary Add": "\ue82e",
    "Dictionary Cloud": "\uebc3",
    Dictionary: "\ue82d",
    "Direct Access": "\ue83b",
    Directions: "\ue8f0",
    "Disable Updates": "\ue8d8",
    "Disconnect Display": "\uea14",
    "Disconnect Drive": "\ue8cd",
    Dislike: "\ue8e0",
    DMC: "\ue951",
    "Dock Bottom": "\ue90e",
    "Dock Left Mirrored": "\uea4c",
    "Dock Left": "\ue90c",
    "Dock Right Mirrored": "\uea4b",
    "Dock Right": "\ue90d",
    "Dock Top": "\ue66a",
    Dock: "\ue952",
    "Document Approval": "\uf28b",
    Document: "\ue8a5",
    "Double Pinyin": "\uf085",
    "Down Shift Key": "\ue84a",
    Down: "\ue74b",
    "Download Map": "\ue826",
    Download: "\ue896",
    Dpad: "\uf10e",
    "Draw Solid": "\uec88",
    Draw: "\uec87",
    "Driving Mode": "\ue7ec",
    Drop: "\ueb42",
    "Dull Sound Key": "\ue9af",
    "Dull Sound": "\ue911",
    "Duplex Landscape One Sided Mirrored": "\uf57f",
    "Duplex Landscape One Sided": "\uf57e",
    "Duplex Landscape Two Sided Long Edge Mirrored": "\uf581",
    "Duplex Landscape Two Sided Long Edge": "\uf580",
    "Duplex Landscape Two Sided Short Edge Mirrored": "\uf583",
    "Duplex Landscape Two Sided Short Edge": "\uf582",
    "Duplex Portrait One Sided Mirrored": "\uf585",
    "Duplex Portrait One Sided": "\uf584",
    "Duplex Portrait Two Sided Long Edge Mirrored": "\uf587",
    "Duplex Portrait Two Sided Long Edge": "\uf586",
    "Duplex Portrait Two Sided Short Edge Mirrored": "\uf589",
    "Duplex Portrait Two Sided Short Edge": "\uf588",
    "Dynamic Lock": "\uf439",
    Ear: "\uf270",
    Earbud: "\uf4c0",
    "Ease Of Access": "\ue776",
    "Edit Mirrored": "\ueb7e",
    "Edit Style": "\uef60",
    Edit: "\ue70f",
    "Education Icon": "\uf7bb",
    Education: "\ue7be",
    Eject: "\uf847",
    EMI: "\ue731",
    "Emoji 2": "\ue76e",
    "Emoji Swatch": "\ued5b",
    "Emoji Tab Celebration Objects": "\ued55",
    "Emoji Tab Favorites": "\ued5a",
    "Emoji Tab Food Plants": "\ued56",
    "Emoji Tab More Symbols": "\uf6ba",
    "Emoji Tab People": "\ued53",
    "Emoji Tab Smiles Animals": "\ued54",
    "Emoji Tab Symbols": "\ued58",
    "Emoji Tab Text Smiles": "\ued59",
    "Emoji Tab Transit Places": "\ued57",
    Emoji: "\ue899",
    "End Point Solid": "\ueb4b",
    "End Point": "\ue81b",
    "English Punctuation": "\uf110",
    Equalizer: "\ue9e9",
    "Erase Tool Fill 2": "\ue82c",
    "Erase Tool Fill": "\ue82b",
    "Erase Tool": "\ue75c",
    "Error Badge 12": "\uedae",
    "Error Badge": "\uea39",
    Error: "\ue783",
    "eSIM Busy": "\uf61e",
    "eSIM Locked": "\uf61d",
    "eSIM No Profile": "\uf61c",
    eSIM: "\uf61b",
    "Ethernet Error": "\ueb55",
    Ethernet: "\ue839",
    "Ethernet Warning": "\ueb56",
    "Event 12": "\uf763",
    "Expand Tile Mirrored": "\uea4e",
    "Expand Tile": "\ue976",
    "Exploit Protection Settings": "\uf259",
    "Exploit Protection": "\uf8a6",
    "Explore Content Single": "\uf164",
    "Explore Content": "\ueccd",
    "Export Mirrored": "\uede2",
    Export: "\uede1",
    "Expressive Input Entry": "\uf6b8",
    "Eye Gaze": "\uf19d",
    Eyedropper: "\uef3c",
    Family: "\uebda",
    "Fast Forward": "\ueb9d",
    "Favicon 2": "\uec6c",
    Favicon: "\ue737",
    "Favorite List": "\ue728",
    "Favorite Star Fill": "\ue735",
    "Favorite Star": "\ue734",
    "Feedback App": "\ue939",
    Feedback: "\ued15",
    "Ferry Solid": "\ueb48",
    Ferry: "\ue7e3",
    "File Explorer App": "\uec51",
    "File Explorer": "\uec50",
    Filter: "\ue71c",
    "Finger Inking": "\ued5f",
    Fingerprint: "\ue928",
    "Fit Page": "\ue9a6",
    Flag: "\ue7c1",
    Flashlight: "\ue754",
    "Flick Down": "\ue935",
    "Flick Left": "\ue937",
    "Flick Right": "\ue938",
    "Flick Up": "\ue936",
    Flow: "\uef90",
    "Folder Fill": "\ue8d5",
    "Folder Horizontal": "\uf12b",
    "Folder Open": "\ue838",
    "Folder Select": "\uf89a",
    Folder: "\ue8b7",
    "Font Color": "\ue8d3",
    "Font Decrease": "\ue8e7",
    "Font Increase": "\ue8e8",
    "Font Size": "\ue8e9",
    Font: "\ue8d2",
    "Forward Call": "\ueac2",
    "Forward Mirrored": "\uf0d3",
    "Forward Sm": "\ue9ac",
    "Forward Solid Bold": "\uf8ad",
    Forward: "\ue72a",
    "Four Bars": "\ue908",
    "Free Form Clipping": "\uf408",
    Frigid: "\ue9ca",
    "Full 20": "\uf741",
    "Full Alpha": "\ue97f",
    "Full Circle Mask": "\ue91f",
    "Full Hiragana": "\ue986",
    "Full Katakana": "\ue987",
    "Full Screen": "\ue740",
    "Fuzzy Reading": "\uf5ef",
    "Game Console": "\ue967",
    Game: "\ue7fc",
    "Generic Scan": "\uee6f",
    GIF: "\uf4a9",
    "Giftbox Open": "\uf133",
    "Global Navigation Button": "\ue700",
    "Globe 2": "\uf49a",
    Globe: "\ue774",
    "Go Mirrored": "\uea4f",
    "Go To Message": "\uf716",
    "Go To Start": "\ue8fc",
    Go: "\ue8ad",
    "Goto Today": "\ue8d1",
    Grapes: "\ueabe",
    "Grid View Small": "\uf232",
    "Grid View": "\uf0e2",
    "Gripper Bar Horizontal": "\ue76f",
    "Gripper Bar Vertical": "\ue784",
    "Gripper Resize Mirrored": "\uea50",
    "Gripper Resize": "\ue788",
    "Gripper Tool": "\ue75e",
    Groceries: "\uec09",
    "Group List": "\uf168",
    Group: "\ue902",
    "Guest User": "\uee57",
    "Half Alpha": "\ue97e",
    "Half Dull Sound": "\ue9b0",
    "Half Katakana": "\ue988",
    "Half Star Left": "\ue7c6",
    "Half Star Right": "\ue7c7",
    "Handwriting 20": "\uf742",
    Handwriting: "\ue929",
    "Hang Up": "\ue778",
    "Hard Drive": "\ueda2",
    "Headless Device": "\uf191",
    "Headphone 0": "\ued30",
    "Headphone 1": "\ued31",
    "Headphone 2": "\ued32",
    "Headphone 3": "\ued33",
    Headphone: "\ue7f6",
    Headset: "\ue95b",
    Health: "\ue95e",
    "Heart Broken": "\uea92",
    "Heart Fill": "\ueb52",
    Heart: "\ueb51",
    "Height Map": "\uf120",
    "Help Mirrored": "\uea51",
    Help: "\ue897",
    "Hide Bcc": "\ue8c5",
    Hide: "\ued1a",
    "Highlight Fill 2": "\ue82a",
    "Highlight Fill": "\ue891",
    Highlight: "\ue7e6",
    History: "\ue81c",
    HMD: "\uf119",
    "Hole Punch Landscape Bottom": "\uf597",
    "Hole Punch Landscape Left": "\uf594",
    "Hole Punch Landscape Right": "\uf595",
    "Hole Punch Landscape Top": "\uf596",
    "Hole Punch Off": "\uf58f",
    "Hole Punch Portrait Bottom": "\uf593",
    "Hole Punch Portrait Left": "\uf590",
    "Hole Punch Portrait Right": "\uf591",
    "Hole Punch Portrait Top": "\uf592",
    "Holo Lens Selected": "\uf4bf",
    "Home Group": "\uec26",
    "Home Solid": "\uea8a",
    Home: "\ue80f",
    "Horizontal Tab Key": "\ue7fd",
    "HWP Insert": "\uf461",
    "HWP Join": "\uf460",
    "HWP New Line": "\uf465",
    "HWP Overwrite": "\uf466",
    "HWP Scratch Out": "\uf463",
    "HWP Split": "\uf464",
    "HWP Strike Through": "\uf462",
    "IBeam Outline": "\ue934",
    IBeam: "\ue933",
    IDBadge: "\uf427",
    "Image Export": "\uee71",
    "Import All Mirrored": "\uea53",
    "Import All": "\ue8b6",
    "Import Mirrored": "\uea52",
    Import: "\ue8b5",
    "Important Badge 12": "\uedb1",
    Important: "\ue8c9",
    "In Private": "\ue727",
    "Incident Triangle": "\ue814",
    "Incoming Call": "\ue77e",
    "Info 2": "\uea1f",
    "Info Solid": "\uf167",
    Info: "\ue946",
    "Inking Caret": "\ued65",
    "Inking Color Fill": "\ued67",
    "Inking Color Outline": "\ued66",
    "Inking Tool Fill 2": "\ue829",
    "Inking Tool Fill": "\ue88f",
    "Inking Tool": "\ue76d",
    Input: "\ue961",
    "Insider Hub App": "\uec24",
    "Instert Words Fill": "\uf7b2",
    "Instert Words": "\uf7b1",
    "Interactive Dashboard": "\uf404",
    "Internet Sharing": "\ue704",
    IOT: "\uf22c",
    Italic: "\ue8db",
    Japanese: "\ue985",
    "Join Words Fill": "\uf7b4",
    "Join Words": "\uf7b3",
    "Jpn Romanji Lock": "\ue87d",
    "Jpn Romanji Shift Lock": "\ue87f",
    "Jpn Romanji Shift": "\ue87e",
    "Jpn Romanji": "\ue87c",
    "Key 12 On": "\ue980",
    "Keyboard 12 Key": "\uf261",
    "Keyboard Brightness": "\ued39",
    "Keyboard Classic": "\ue765",
    "Keyboard Dismiss": "\ue92f",
    "Keyboard Dock": "\uf26b",
    "Keyboard Full": "\uec31",
    "Keyboard Left Aligned": "\uf20c",
    "Keyboard Left Dock": "\uf26d",
    "Keyboard Left Handed": "\ue763",
    "Keyboard Lower Brightness": "\ued3a",
    "Keyboard Narrow": "\uf260",
    "Keyboard One Handed": "\ued4c",
    "Keyboard Right Aligned": "\uf20d",
    "Keyboard Right Dock": "\uf26e",
    "Keyboard Right Handed": "\ue764",
    "Keyboard Settings": "\uf210",
    "Keyboard Shortcut": "\ueda7",
    "Keyboard Split": "\ue766",
    "Keyboard Standard": "\ue92e",
    "Keyboard Undock": "\uf26c",
    "Keyboardsettings 20": "\uf73d",
    Kiosk: "\uf712",
    "Knowledge Article": "\uf000",
    Korean: "\ue97d",
    Label: "\ue932",
    Lamp: "\ueb19",
    "Landscape Orientation Mirrored": "\uf56f",
    "Landscape Orientation": "\uef6b",
    "Lang JPN": "\ue7de",
    "Language Chs": "\ue88d",
    "Language Cht": "\ue88c",
    "Language Jpn": "\uec45",
    "Language Kor": "\ue88b",
    "Laptop Secure": "\uf552",
    "Laptop Selected": "\uec76",
    "Large Erase": "\uf12a",
    Leaf: "\ue8be",
    "Learning Tools": "\uf7db",
    "Leave Chat Mirrored": "\uea54",
    "Leave Chat": "\ue89b",
    LEDLight: "\ue781",
    "Left Arrow Key Time 0": "\uec52",
    "Left Double Quote": "\ue9b2",
    "Left Quote": "\ue848",
    "Left Stick": "\uf108",
    Lexicon: "\uf180",
    Library: "\ue8f1",
    Light: "\ue793",
    Lightbulb: "\uea80",
    "Lightning Bolt": "\ue945",
    "Like Dislike": "\ue8df",
    Like: "\ue8e1",
    "Line Display": "\uef3d",
    Link: "\ue71b",
    "List Mirrored": "\uea55",
    List: "\uea37",
    "Locale Language": "\uf2b7",
    Location: "\ue81d",
    "Lock Feedback": "\uebdb",
    "Lock Screen Glance": "\uee65",
    Lock: "\ue72e",
    "Lockscreen Desktop": "\uee3f",
    "Lower Brightness": "\uec8a",
    "Mag Stripe Reader": "\uec5c",
    "Mail Badge 12": "\uedb3",
    "Mail Fill": "\ue8a8",
    "Mail Forward Mirrored": "\uea56",
    "Mail Forward": "\ue89c",
    "Mail Reply All Mirrored": "\uea58",
    "Mail Reply All": "\ue8c2",
    "Mail Reply Mirrored": "\uea57",
    "Mail Reply": "\ue8ca",
    Mail: "\ue715",
    Manage: "\ue912",
    "Map Compass Bottom": "\ue813",
    "Map Compass Top": "\ue812",
    "Map Directions": "\ue816",
    "Map Drive": "\ue8ce",
    "Map Layers": "\ue81e",
    "Map Pin 2": "\ue7b7",
    "Map Pin": "\ue707",
    Marker: "\ued64",
    "Market Down": "\uef42",
    Market: "\ueafc",
    Marquee: "\uef20",
    "Media Storage Tower": "\ue965",
    Media: "\uea69",
    Medical: "\uead4",
    Megaphone: "\ue789",
    Memo: "\ue77c",
    "Merge Call": "\uea3c",
    Message: "\ue8bd",
    "Mic Clipping": "\uec72",
    "Mic Error": "\uec56",
    "Mic Off 2": "\uf781",
    "Mic Off": "\uec54",
    "Mic On": "\uec71",
    "Mic Sleep": "\uec55",
    "Microphone Listening": "\uf12e",
    "Microphone Solid Bold": "\uf8b1",
    Microphone: "\ue720",
    "Mini Contract 2 Mirrored": "\uee49",
    "Mini Expand 2 Mirrored": "\uee47",
    "Miracast Logo Large": "\uec16",
    "Miracast Logo Small": "\uec15",
    "Mix Volumes": "\uf4c3",
    "Mixed Media Badge": "\uea0d",
    "Mob Action Center": "\uec42",
    "Mob Airplane": "\uec40",
    "Mob Battery 0": "\ueba0",
    "Mob Battery 1": "\ueba1",
    "Mob Battery 10": "\uebaa",
    "Mob Battery 2": "\ueba2",
    "Mob Battery 3": "\ueba3",
    "Mob Battery 4": "\ueba4",
    "Mob Battery 5": "\ueba5",
    "Mob Battery 6": "\ueba6",
    "Mob Battery 7": "\ueba7",
    "Mob Battery 8": "\ueba8",
    "Mob Battery 9": "\ueba9",
    "Mob Battery Charging 0": "\uebab",
    "Mob Battery Charging 1": "\uebac",
    "Mob Battery Charging 10": "\uebb5",
    "Mob Battery Charging 2": "\uebad",
    "Mob Battery Charging 3": "\uebae",
    "Mob Battery Charging 4": "\uebaf",
    "Mob Battery Charging 5": "\uebb0",
    "Mob Battery Charging 6": "\uebb1",
    "Mob Battery Charging 7": "\uebb2",
    "Mob Battery Charging 8": "\uebb3",
    "Mob Battery Charging 9": "\uebb4",
    "Mob Battery Saver 0": "\uebb6",
    "Mob Battery Saver 1": "\uebb7",
    "Mob Battery Saver 10": "\uebc0",
    "Mob Battery Saver 2": "\uebb8",
    "Mob Battery Saver 3": "\uebb9",
    "Mob Battery Saver 4": "\uebba",
    "Mob Battery Saver 5": "\uebbb",
    "Mob Battery Saver 6": "\uebbc",
    "Mob Battery Saver 7": "\uebbd",
    "Mob Battery Saver 8": "\uebbe",
    "Mob Battery Saver 9": "\uebbf",
    "Mob Battery Unknown": "\uec02",
    "Mob Bluetooth": "\uec41",
    "Mob Call Forwarding Mirrored": "\uec7f",
    "Mob Call Forwarding": "\uec7e",
    "Mob Driving Mode": "\uec47",
    "Mob eSIM Busy": "\ued2d",
    "Mob eSIM Locked": "\ued2c",
    "Mob eSIM No Profile": "\ued2b",
    "Mob eSIM": "\ued2a",
    "Mob Location": "\uec43",
    "Mob Quiet Hours": "\uec46",
    "Mob Signal 1": "\uec37",
    "Mob Signal 2": "\uec38",
    "Mob Signal 3": "\uec39",
    "Mob Signal 4": "\uec3a",
    "Mob Signal 5": "\uec3b",
    "Mob SIM Error": "\uf5ab",
    "Mob SIM Lock": "\ue875",
    "Mob SIM Missing": "\ue876",
    "Mob Wifi 1": "\uec3c",
    "Mob Wifi 2": "\uec3d",
    "Mob Wifi 3": "\uec3e",
    "Mob Wifi 4": "\uec3f",
    "Mob Wifi Hotspot": "\uec44",
    "Mob Wifi Warning 1": "\uf473",
    "Mob Wifi Warning 2": "\uf474",
    "Mob Wifi Warning 3": "\uf475",
    "Mob Wifi Warning 4": "\uf476",
    "Mobile Locked": "\uec20",
    "Mobile Selected": "\uec75",
    "Mobile Tablet": "\ue8cc",
    More: "\ue712",
    Mouse: "\ue962",
    "Move To Folder": "\ue8de",
    Move: "\ue7c2",
    Movies: "\ue8b2",
    "Multi Select Mirrored": "\uea98",
    "Multi Select": "\ue762",
    "Multimedia DMP": "\ued47",
    "Multimedia DMS": "\ue953",
    "Multimedia DVR": "\ue954",
    "Multimedia PMP": "\ue955",
    "Music Album": "\ue93c",
    "Music Info": "\ue90b",
    "Music Note": "\uec4f",
    "Music Sharing Off": "\uf624",
    "Music Sharing": "\uf623",
    Mute: "\ue74f",
    "My Network": "\uec27",
    "Narrator App": "\uf83b",
    "Narrator Forward Mirrored": "\uedaa",
    "Narrator Forward": "\ueda9",
    Narrator: "\ued4d",
    "Nearby Sharing": "\uf3e2",
    "Network Adapter": "\ueda3",
    "Network Connected Checkmark": "\uf386",
    "Network Connected": "\uf385",
    "Network Offline": "\uf384",
    "Network Physical": "\uf211",
    "Network Printer": "\ueda5",
    "Network Sharing": "\uf193",
    "Network Tower": "\uec05",
    Network: "\ue968",
    "New Folder": "\ue8f4",
    "New Window": "\ue78b",
    "Next Solid": "\ue623",
    Next: "\ue893",
    "Noise Cancelation Off": "\uf620",
    "Noise Cancelation": "\uf61f",
    "NUI Face": "\ueb68",
    "NUI FP Continue Slide Action": "\ueb85",
    "NUI FP Continue Slide Hand": "\ueb84",
    "NUI FP Press Action": "\ueb8b",
    "NUI FP Press Hand": "\ueb8a",
    "NUI FP Press Repeat Action": "\ueb8d",
    "NUI FP Press Repeat Hand": "\ueb8c",
    "NUI FP Roll Left Action": "\ueb89",
    "NUI FP Roll Left Hand": "\ueb88",
    "NUI FP Roll Right Hand Action": "\ueb87",
    "NUI FP Roll Right Hand": "\ueb86",
    "NUI FP Start Slide Action": "\ueb83",
    "NUI FP Start Slide Hand": "\ueb82",
    "NUI Iris": "\ueb67",
    OEM: "\ue74c",
    "One Bar": "\ue905",
    "One Handed Left 20": "\uf73f",
    "One Handed Right 20": "\uf73e",
    "Open File": "\ue8e5",
    "Open Folder Horizontal": "\ued25",
    "Open In New Window": "\ue8a7",
    "Open Local": "\ue8da",
    "Open Pane Mirrored": "\uea5b",
    "Open Pane": "\ue8a0",
    "Open With Mirrored": "\uea5c",
    "Open With": "\ue7ac",
    Orientation: "\ue8b4",
    "Other User": "\ue7ee",
    "Outline Half Star Left": "\uf0e7",
    "Outline Half Star Right": "\uf0e8",
    "Outline Quarter Star Left": "\uf0e5",
    "Outline Quarter Star Right": "\uf0e6",
    "Outline Star Left Half": "\uf0f7",
    "Outline Star Right Half": "\uf0f8",
    "Outline Three Quarter Star Left": "\uf0e9",
    "Outline Three Quarter Star Right": "\uf0ea",
    "Overwrite Words Fill Korean": "\uf7ba",
    "Overwrite Words Fill": "\uf7b6",
    "Overwrite Words Korean": "\uf7b9",
    "Overwrite Words": "\uf7b5",
    Package: "\ue7b8",
    "Page Left": "\ue760",
    "Page Margin Landscape Moderate": "\uf579",
    "Page Margin Landscape Narrow": "\uf577",
    "Page Margin Landscape Normal": "\uf578",
    "Page Margin Landscape Wide": "\uf57a",
    "Page Margin Portrait Moderate": "\uf575",
    "Page Margin Portrait Narrow": "\uf573",
    "Page Margin Portrait Normal": "\uf574",
    "Page Margin Portrait Wide": "\uf576",
    "Page Mirrored": "\uf56e",
    "Page Right": "\ue761",
    "Page Solid": "\ue729",
    Page: "\ue7c3",
    "Pagination Dot Outline 10": "\uf126",
    "Pagination Dot Solid 10": "\uf127",
    "Pan Mode": "\uece9",
    "Parking Location Mirrored": "\uea5e",
    "Parking Location Solid": "\uea8b",
    "Parking Location": "\ue811",
    "Party Leader": "\ueca7",
    "Passive Authentication": "\uf32a",
    "Password Key Hide": "\ue9a9",
    "Password Key Show": "\ue9a8",
    "Paste Linked": "\ue630",
    Paste: "\ue77f",
    "Pause Badge 12": "\uedb4",
    "Pause Bold": "\uf8ae",
    "Pause Solid": "\ue62e",
    Pause: "\ue769",
    "Payment Card": "\ue8c7",
    "PC 1": "\ue977",
    PDF: "\uea90",
    "Pen Palette Mirrored": "\uef16",
    "Pen Palette": "\uee56",
    "Pen Tips Mirrored": "\uf45f",
    "Pen Tips": "\uf45e",
    "Pen Workspace Mirrored": "\uef15",
    "Pen Workspace": "\uedc6",
    "Pencil Fill": "\uf0c6",
    Pencil: "\ued63",
    People: "\ue716",
    "Period Key": "\ue843",
    Permissions: "\ue8d7",
    "Personal Folder": "\uec25",
    Personalize: "\ue771",
    "Phone Book": "\ue780",
    "Phone Solid": "\ue626",
    Phone: "\ue717",
    "Photo 2": "\ueb9f",
    Photo: "\ue91b",
    Picture: "\ue8b9",
    "Pie Single": "\ueb05",
    "Pin Fill": "\ue841",
    "Pin Solid": "\uf1db",
    Pin: "\ue718",
    "Pinned Fill": "\ue842",
    Pinned: "\ue840",
    PINPad: "\uef3e",
    "Pinyin IMELogo": "\uede5",
    PLAP: "\uec19",
    "Play 36": "\uee4a",
    "Play Badge 12": "\uedb5",
    "Play Solid": "\uf5b0",
    Play: "\ue768",
    "Playback Rate 1 x": "\uec57",
    "Playback Rate Other": "\uec58",
    "Player Settings": "\uef58",
    POI: "\uecaf",
    "Point Erase Mirrored": "\uef18",
    "Point Erase": "\ued61",
    "Pointer Hand": "\uf271",
    "Police Car": "\uec81",
    "Post Update": "\ue8f3",
    "Power Button": "\ue7e8",
    "Power Button Update": "\uf83d",
    "PPS Four Landscape": "\uf58d",
    "PPS Four Portrait": "\uf58e",
    "PPS One Landscape": "\uf58a",
    "PPS One Portrait": "\uf5ad",
    "PPS Two Landscape": "\uf58b",
    "PPS Two Portrait": "\uf58c",
    "Presence Chicklet": "\ue978",
    "Presence Chicklet Video": "\ue979",
    "Preview Link": "\ue8a1",
    Preview: "\ue8ff",
    "Previous Solid": "\ue622",
    Previous: "\ue892",
    "Print All Pages": "\uf571",
    "Print Custom Range": "\uf572",
    "Print Default": "\uf56d",
    Print: "\ue749",
    "Printer 3D": "\ue914",
    "Printfax Printer File": "\ue956",
    Priority: "\ue8d0",
    "Private Call": "\uea3d",
    Process: "\ue9f3",
    Processing: "\ue9f5",
    "Productivity Mode": "\uf71e",
    "Progress Ring Dots": "\uf16a",
    Project: "\uebc6",
    Projector: "\ue95d",
    "Protected Document": "\ue8a6",
    Protractor: "\uf0b4",
    "Provisioning Package": "\ue835",
    "Punc Key 0": "\ue84c",
    "Punc Key 1": "\ue9b4",
    "Punc Key 2": "\ue9b5",
    "Punc Key 3": "\ue9b6",
    "Punc Key 4": "\ue9b7",
    "Punc Key 5": "\ue9b8",
    "Punc Key 6": "\ue9b9",
    "Punc Key 7": "\ue9bb",
    "Punc Key 8": "\ue9bc",
    "Punc Key 9": "\ue9ba",
    "Punc Key Left Bottom": "\ue84d",
    "Punc Key Right Bottom": "\ue9b3",
    "Punc Key": "\ue844",
    Puzzle: "\uea86",
    QRCode: "\ued14",
    "Quarentined Items Mirrored": "\uf0b3",
    "Quarentined Items": "\uf0b2",
    "Quarter Star Left": "\uf0ca",
    "Quarter Star Right": "\uf0cb",
    "Quick Note": "\ue70b",
    "Quiet Hours Badge 12": "\uf0ce",
    "Quiet Hours": "\ue708",
    "QWERTY Off": "\ue983",
    "QWERTY On": "\ue982",
    Radar: "\ueb44",
    "Radio Btn Off": "\uecca",
    "Radio Btn On": "\ueccb",
    "Radio Bullet 2": "\ueccc",
    "Radio Bullet": "\ue915",
    "Read Out Loud": "\uf112",
    Read: "\ue8c3",
    "Reading List": "\ue7bc",
    "Reading Mode": "\ue736",
    "Receipt Printer": "\uec5b",
    Recent: "\ue823",
    "Record 2": "\uea3f",
    Record: "\ue7c8",
    "Rectangular Clipping": "\uf407",
    "Red Eye": "\ue7b3",
    Redo: "\ue7a6",
    Refresh: "\ue72c",
    Relationship: "\uf003",
    "Remembered Device": "\ue70c",
    "Reminder Fill": "\ueb4f",
    Reminder: "\ueb50",
    Remote: "\ue8af",
    "Remove From": "\uecc9",
    Remove: "\ue738",
    Rename: "\ue8ac",
    Repair: "\ue90f",
    "Repeat All": "\ue8ee",
    "Repeat Off": "\uf5e7",
    "Repeat One": "\ue8ed",
    Replay: "\uef3b",
    "Reply Mirrored": "\uee35",
    Reply: "\ue97a",
    "Report Document": "\ue9f9",
    "Report Hacked": "\ue730",
    "Reset Device": "\ued10",
    "Reset Drive": "\uebc4",
    Reshare: "\ue8eb",
    "Resize Mouse Large": "\ue747",
    "Resize Mouse Medium Mirrored": "\uea5f",
    "Resize Mouse Medium": "\ue744",
    "Resize Mouse Small Mirrored": "\uea60",
    "Resize Mouse Small": "\ue743",
    "Resize Mouse Tall Mirrored": "\uea61",
    "Resize Mouse Tall": "\ue746",
    "Resize Mouse Wide": "\ue745",
    "Resize Touch Larger": "\ue741",
    "Resize Touch Narrower Mirrored": "\uea62",
    "Resize Touch Narrower": "\ue7ea",
    "Resize Touch Shorter": "\ue7eb",
    "Resize Touch Smaller": "\ue742",
    "Restart Update": "\uf83e",
    "Return Key Lg": "\ueb97",
    "Return Key Sm": "\ue966",
    "Return Key": "\ue751",
    "Return To Call": "\uf71a",
    "Return To Window": "\ue944",
    "Rev Toggle Key": "\ue845",
    "Reveal Password Medium": "\uf78d",
    Rewind: "\ueb9e",
    "Right Arrow Key Time 0": "\uebe7",
    "Right Arrow Key Time 1": "\ue846",
    "Right Arrow Key Time 2": "\ue847",
    "Right Arrow Key Time 3": "\ue84e",
    "Right Arrow Key Time 4": "\ue84f",
    "Right Double Quote": "\ue9b1",
    "Right Quote": "\ue849",
    "Right Stick": "\uf109",
    "Ringer Badge 12": "\uedac",
    "Ringer Silent": "\ue7ed",
    Ringer: "\uea8f",
    "Roaming Domestic": "\ue879",
    "Roaming International": "\ue878",
    Robot: "\ue99a",
    "Rotate Camera": "\ue89e",
    "Rotate Map Left": "\ue80d",
    "Rotate Map Right": "\ue80c",
    Rotate: "\ue7ad",
    "Rotation Lock": "\ue755",
    "RTT Logo": "\uf714",
    Ruler: "\ued5e",
    Safe: "\uf540",
    "Save As": "\ue792",
    "Save Copy": "\uea35",
    "Save Local": "\ue78c",
    Save: "\ue74e",
    Scan: "\ue8fe",
    "Screen Time": "\uf182",
    "Scroll Mode": "\uece7",
    "Scroll Up Down": "\uec8f",
    SDCard: "\ue7f1",
    "Search And Apps": "\ue773",
    "Search Medium": "\uf78b",
    Search: "\ue721",
    "Secure Chat": "\ue675",
    "Secure Wifi 1": "\ue670",
    "Secure Wifi 2": "\ue671",
    "Secure Wifi 3": "\ue672",
    "Secure Wifi Bars": "\ue674",
    "Secure Wifi": "\ue673",
    "Select All": "\ue8b3",
    "Send Fill Mirrored": "\uea64",
    "Send Fill": "\ue725",
    "Send Mirrored": "\uea63",
    Send: "\ue724",
    Sensor: "\ue957",
    "Set History Status 2": "\uf739",
    "Set History Status": "\uf738",
    "Set Solid": "\uf5ee",
    "Set Tile": "\ue97b",
    Set: "\uf5ed",
    "Setlock Screen": "\ue7b5",
    Setting: "\ue713",
    "Settings Battery": "\uee63",
    "Settings Display Sound": "\ue7f3",
    "Settings Solid": "\uf8b0",
    "Share Broadband": "\ue83a",
    Share: "\ue72d",
    Shield: "\uea18",
    Shop: "\ue719",
    "Shopping Cart": "\ue7bf",
    "Show Bcc": "\ue8c4",
    "Show Results Mirrored": "\uea65",
    "Show Results": "\ue8bc",
    Shuffle: "\ue8b1",
    "Sign Out": "\uf3b1",
    "Signal Bars 1": "\ue86c",
    "Signal Bars 2": "\ue86d",
    "Signal Bars 3": "\ue86e",
    "Signal Bars 4": "\ue86f",
    "Signal Bars 5": "\ue870",
    "Signal Error": "\ued2e",
    "Signal Not Connected": "\ue871",
    "Signal Roaming": "\uec1e",
    "Signature Capture": "\uef3f",
    "SIM Error": "\uf618",
    "SIM Lock": "\uf61a",
    "SIM Missing": "\uf619",
    SIPMove: "\ue759",
    SIPRedock: "\ue75b",
    SIPUndock: "\ue75a",
    Size: "\ue61f",
    "Skip Back 10": "\ued3c",
    "Skip Forward 30": "\ued3d",
    "Slider Thumb": "\uec13",
    Slideshow: "\ue786",
    "Slow Motion On": "\uea79",
    "Small Erase": "\uf129",
    "Smart Screen": "\uf8a5",
    Smartcard: "\ue963",
    "Smartcard Virtual": "\ue964",
    Snooze: "\uf4bd",
    Sort: "\ue8cb",
    "Spatial Volume 0": "\uf0eb",
    "Spatial Volume 1": "\uf0ec",
    "Spatial Volume 2": "\uf0ed",
    "Spatial Volume 3": "\uf0ee",
    Speakers: "\ue7f5",
    "Special Effect Size": "\uf4a5",
    "Speech Solid Bold": "\uf8b2",
    Speech: "\uefa9",
    "Speed High": "\uec4a",
    "Speed Medium": "\uec49",
    "Speed Off": "\uec48",
    "Spelling Chinese": "\uf87e",
    "Spelling Korean": "\uf87c",
    "Spelling Serbian": "\uf87d",
    Spelling: "\uf87b",
    "Split 20": "\uf740",
    "Stapling Landscape Book Binding": "\uf5a9",
    "Stapling Landscape Bottom Left": "\uf5a3",
    "Stapling Landscape Bottom Right": "\uf5a4",
    "Stapling Landscape Top Left": "\uf5a1",
    "Stapling Landscape Top Right": "\uf5a2",
    "Stapling Landscape Two Bottom": "\uf5a8",
    "Stapling Landscape Two Left": "\uf5a5",
    "Stapling Landscape Two Right": "\uf5a6",
    "Stapling Landscape Two Top": "\uf5a7",
    "Stapling Off": "\uf598",
    "Stapling Portrait Book Binding": "\uf5a0",
    "Stapling Portrait Bottom Left": "\uf5ae",
    "Stapling Portrait Bottom Right": "\uf59b",
    "Stapling Portrait Top Left": "\uf599",
    "Stapling Portrait Top Right": "\uf59a",
    "Stapling Portrait Two Bottom": "\uf59f",
    "Stapling Portrait Two Left": "\uf59c",
    "Stapling Portrait Two Right": "\uf59d",
    "Stapling Portrait Two Top": "\uf59e",
    "Start Point Solid": "\ueb49",
    "Start Point": "\ue819",
    "Start Presenting": "\uf71c",
    "Status Checkmark 7": "\uf0b7",
    "Status Checkmark Left": "\uf1d9",
    "Status Checkmark": "\uf1d8",
    "Status Circle 7": "\uf0b6",
    "Status Circle Block 2": "\uf141",
    "Status Circle Block": "\uf140",
    "Status Circle Checkmark": "\uf13e",
    "Status Circle Error X": "\uf13d",
    "Status Circle Exclamation": "\uf13c",
    "Status Circle Info": "\uf13f",
    "Status Circle Inner": "\uf137",
    "Status Circle Left": "\uebfd",
    "Status Circle Outer": "\uf136",
    "Status Circle Question Mark": "\uf142",
    "Status Circle Ring": "\uf138",
    "Status Circle Sync": "\uf143",
    "Status Circle": "\uea81",
    "Status Connecting 1": "\ueb57",
    "Status Connecting 2": "\ueb58",
    "Status Data Transfer Roaming": "\uf5aa",
    "Status Data Transfer": "\ue880",
    "Status Data Transfer VPN": "\ue881",
    "Status Dual SIM 1": "\ue884",
    "Status Dual SIM 1 VPN": "\ue885",
    "Status Dual SIM 2": "\ue882",
    "Status Dual SIM 2 VPN": "\ue883",
    "Status Error Circle 7": "\uf0b8",
    "Status Error Full": "\ueb90",
    "Status Error Left": "\uebff",
    "Status Error": "\uea83",
    "Status Exclamation Circle 7": "\uf12f",
    "Status Info Left": "\uf3cd",
    "Status Info": "\uf3cc",
    "Status Pause 7": "\uf175",
    "Status Secured": "\uf809",
    "Status SG LTE Cell": "\ue887",
    "Status SG LTE Data VPN": "\ue888",
    "Status SG LTE": "\ue886",
    "Status Triangle Exclamation": "\uf13b",
    "Status Triangle Inner": "\uf13a",
    "Status Triangle Left": "\uebfe",
    "Status Triangle Outer": "\uf139",
    "Status Triangle": "\uea82",
    "Status Unsecure": "\ueb59",
    "Status VPN": "\ue889",
    "Status Warning Left": "\uec00",
    "Status Warning": "\uea84",
    "Sticker 2": "\uf4aa",
    "Stock Down": "\ueb0f",
    "Stock Up": "\ueb11",
    "Stop Point Solid": "\ueb4a",
    "Stop Point": "\ue81a",
    "Stop Presenting": "\uf71d",
    "Stop Solid": "\uee95",
    Stop: "\ue71a",
    Stopwatch: "\ue916",
    "Storage Network Wireless": "\ue969",
    "Storage Optical": "\ue958",
    "Storage Tape": "\ue96a",
    "Streaming Enterprise": "\ued2f",
    Streaming: "\ue93e",
    Street: "\ue913",
    "Streetside Split Expand": "\ue803",
    "Streetside Split Minimize": "\ue802",
    Strikethrough: "\uede0",
    "Stroke Erase 2": "\uf128",
    "Stroke Erase Mirrored": "\uef17",
    "Stroke Erase": "\ued60",
    "Subscription Add Mirrored": "\ued11",
    "Subscription Add": "\ued0e",
    "Subtitles Audio": "\ued1f",
    Subtitles: "\ued1e",
    "Subtract Bold": "\uf8ab",
    "Surface Hub Selected": "\uf4be",
    "Surface Hub": "\ue8ae",
    Sustainable: "\uec0a",
    "Swipe Reveal Art": "\uec6d",
    Swipe: "\ue927",
    "Switch Apps": "\ue8f9",
    Switch: "\ue8ab",
    "Switch User": "\ue748",
    "Sync Badge 12": "\uedab",
    "Sync Error": "\uea6a",
    "Sync Folder": "\ue8f7",
    Sync: "\ue895",
    System: "\ue770",
    "Tablet Mode": "\uebfc",
    "Tablet Selected": "\uec74",
    Tablet: "\ue70a",
    Tag: "\ue8ec",
    "Tap And Send": "\ue9a1",
    Task: "\uf7ec",
    "Task View Expanded": "\ueb91",
    "Task View Settings": "\uee40",
    "Task View": "\ue7c4",
    "Taskbar Phone": "\uee64",
    "This PC": "\uec4e",
    "Thought Bubble": "\uea91",
    "Three Bars": "\ue907",
    "Three Quarter Star Left": "\uf0cc",
    "Three Quarter Star Right": "\uf0cd",
    Tiles: "\ueca5",
    "Tilt Down": "\ue80a",
    "Tilt Up": "\ue809",
    "Time Language": "\ue775",
    "Toggle Border": "\uec12",
    "Toggle Filled": "\uec11",
    "Toggle Left": "\uf19e",
    "Toggle Right": "\uf19f",
    "Toggle Thumb": "\uec14",
    "Toll Solid": "\uf161",
    "Tool Tip": "\ue82f",
    "Touch Pointer": "\ue7c9",
    Touch: "\ue815",
    Touchpad: "\uefa5",
    Touchscreen: "\ueda4",
    "Trackers Mirrored": "\uee92",
    Trackers: "\ueadf",
    "Traffic Congestion Solid": "\uf163",
    "Traffic Light": "\uef31",
    "Train Solid": "\ueb4d",
    Train: "\ue7c0",
    Transcribe: "\ue66d",
    "Tree Folder Folder Fill": "\ued42",
    "Tree Folder Folder Open Fill": "\ued44",
    "Tree Folder Folder Open": "\ued43",
    "Tree Folder Folder": "\ued41",
    "Trigger Left": "\uf10a",
    "Trigger Right": "\uf10b",
    Trim: "\ue78a",
    "TVMonitor Selected": "\uec77",
    TVMonitor: "\ue7f4",
    "Two Bars": "\ue906",
    "Two Page": "\ue89a",
    Type: "\ue97c",
    "U+E614": "\ue614",
    "U+E615": "\ue615",
    "U+E616": "\ue616",
    "U+E617": "\ue617",
    "U+E618": "\ue618",
    "U+E620": "\ue620",
    "U+E621": "\ue621",
    "U+E624": "\ue624",
    "U+E625": "\ue625",
    "U+E629": "\ue629",
    "U+E62B": "\ue62b",
    "U+E64B": "\ue64b",
    "Arrow Up": "\ue64c",
    "Arrow Right": "\ue64d",
    "Arrow Left": "\ue64e",
    "U+E64F": "\ue64f",
    "U+E650": "\ue650",
    "U+E651": "\ue651",
    "U+E652": "\ue652",
    "U+E65A": "\ue65a",
    "U+E65B": "\ue65b",
    "U+E65F": "\ue65f",
    "U+E679": "\ue679",
    "U+E67A": "\ue67a",
    "U+E794": "\ue794",
    "U+E833": "\ue833",
    "U+EAA1": "\ueaa1",
    "U+EAA2": "\ueaa2",
    "U+EAA4": "\ueaa4",
    "U+EAA5": "\ueaa5",
    "U+EAA8": "\ueaa8",
    "U+EAAA": "\ueaaa",
    "U+EAAE": "\ueaae",
    "U+EABB": "\ueabb",
    "U+EABC": "\ueabc",
    "U+EAD5": "\uead5",
    "U+EAD6": "\uead6",
    "U+EAD7": "\uead7",
    "U+EADD": "\ueadd",
    "U+EAE1": "\ueae1",
    "U+EB16": "\ueb16",
    "U+EB17": "\ueb17",
    "U+EB1A": "\ueb1a",
    "U+EB1D": "\ueb1d",
    "U+EB3B": "\ueb3b",
    "U+EB77": "\ueb77",
    "U+EC34": "\uec34",
    "U+EC91": "\uec91",
    "U+EC94": "\uec94",
    "U+ED21": "\ued21",
    "U+EE41": "\uee41",
    "U+EE42": "\uee42",
    "U+EE43": "\uee43",
    "U+EE44": "\uee44",
    "U+EE45": "\uee45",
    "U+EE7E": "\uee7e",
    "U+EEA0": "\ueea0",
    "U+EEA1": "\ueea1",
    "U+EF97": "\uef97",
    "U+EFFF": "\uefff",
    "U+F06C": "\uf06c",
    "U+F0F6": "\uf0f6",
    "U+F117": "\uf117",
    "U+F15F": "\uf15f",
    "U+F1B1": "\uf1b1",
    "U+F1C6": "\uf1c6",
    "U+F1E8": "\uf1e8",
    "U+F27C": "\uf27c",
    "U+F27F": "\uf27f",
    "U+F285": "\uf285",
    "U+F2A3": "\uf2a3",
    "U+F2A5": "\uf2a5",
    "U+F2A8": "\uf2a8",
    "U+F39B": "\uf39b",
    "U+F432": "\uf432",
    "U+F47F": "\uf47f",
    "U+F67B": "\uf67b",
    "U+F683": "\uf683",
    "U+F684": "\uf684",
    "U+F698": "\uf698",
    "U+F8C0": "\uf8c0",
    "U+F8C1": "\uf8c1",
    "U+F8C2": "\uf8c2",
    "U+F8C3": "\uf8c3",
    "U+F8C4": "\uf8c4",
    "U+F8C5": "\uf8c5",
    "U+F8C6": "\uf8c6",
    "U+F8C7": "\uf8c7",
    "U+F8C8": "\uf8c8",
    "U+F8C9": "\uf8c9",
    "U+F8CA": "\uf8ca",
    "U+F8CB": "\uf8cb",
    "U+F8CC": "\uf8cc",
    Underline: "\ue8dc",
    "Underscore Space": "\ue75d",
    Undo: "\ue7a7",
    Undocked: "\ue66c",
    Unfavorite: "\ue8d9",
    Unit: "\uecc6",
    "Unknown Mirrored": "\uf22e",
    Unknown: "\ue9ce",
    Unlock: "\ue785",
    Unpin: "\ue77a",
    "Unsync Folder": "\ue8f6",
    "Up Arrow Shift Key": "\ue752",
    "Up Shift Key": "\ue84b",
    Up: "\ue74a",
    "Update Restore": "\ue777",
    "Update Status Dot": "\uf83f",
    Upload: "\ue898",
    "USB Safe Connect": "\uecf3",
    USB: "\ue88e",
    "User APN": "\uf081",
    "User Remove": "\uf69b",
    "Vertical Battery 0": "\uf5f2",
    "Vertical Battery 1": "\uf5f3",
    "Vertical Battery 10": "\uf5fc",
    "Vertical Battery 2": "\uf5f4",
    "Vertical Battery 3": "\uf5f5",
    "Vertical Battery 4": "\uf5f6",
    "Vertical Battery 5": "\uf5f7",
    "Vertical Battery 6": "\uf5f8",
    "Vertical Battery 7": "\uf5f9",
    "Vertical Battery 8": "\uf5fa",
    "Vertical Battery 9": "\uf5fb",
    "Vertical Battery Charging 0": "\uf5fd",
    "Vertical Battery Charging 1": "\uf5fe",
    "Vertical Battery Charging 10": "\uf607",
    "Vertical Battery Charging 2": "\uf5ff",
    "Vertical Battery Charging 3": "\uf600",
    "Vertical Battery Charging 4": "\uf601",
    "Vertical Battery Charging 5": "\uf602",
    "Vertical Battery Charging 6": "\uf603",
    "Vertical Battery Charging 7": "\uf604",
    "Vertical Battery Charging 8": "\uf605",
    "Vertical Battery Charging 9": "\uf606",
    "Vertical Battery Unknown": "\uf608",
    Vibrate: "\ue877",
    "Video 360": "\uf131",
    "Video Capture": "\uf7ee",
    "Video Chat": "\ue8aa",
    "Video Solid": "\uea0c",
    Video: "\ue714",
    "View All": "\ue8a9",
    "View Dashboard": "\uf246",
    View: "\ue890",
    "Virtual Machine Group": "\ueea3",
    "Voice Call": "\uf715",
    "Volume 0": "\ue992",
    "Volume 1": "\ue993",
    "Volume 2": "\ue994",
    "Volume 3": "\ue995",
    "Volume Bars": "\uebc5",
    "Volume Disabled": "\uea85",
    Volume: "\ue767",
    VPN: "\ue705",
    "Walk Solid": "\ue726",
    Walk: "\ue805",
    "Warning Solid": "\uf736",
    Warning: "\ue7ba",
    "Web Search": "\uf6fa",
    "Webcam 2": "\ue960",
    Webcam: "\ue8b8",
    Website: "\ueb41",
    Wheel: "\uee94",
    "Wifi 1": "\ue872",
    "Wifi 2": "\ue873",
    "Wifi 3": "\ue874",
    "Wifi Attention Overlay": "\ue998",
    "Wifi Call 0": "\uf658",
    "Wifi Call 1": "\uf659",
    "Wifi Call 2": "\uf65a",
    "Wifi Call 3": "\uf65b",
    "Wifi Call 4": "\uf65c",
    "Wifi Call Bars": "\uf657",
    "Wifi Error 0": "\ueb5a",
    "Wifi Error 1": "\ueb5b",
    "Wifi Error 2": "\ueb5c",
    "Wifi Error 3": "\ueb5d",
    "Wifi Error 4": "\ueb5e",
    "Wifi Ethernet": "\uee77",
    "Wifi Hotspot": "\ue88a",
    Wifi: "\ue701",
    "Wifi Warning 0": "\ueb5f",
    "Wifi Warning 1": "\ueb60",
    "Wifi Warning 2": "\ueb61",
    "Wifi Warning 3": "\ueb62",
    "Wifi Warning 4": "\ueb63",
    "Wind Direction": "\uebe6",
    "Window Close": "\ue653",
    "Window Maximise": "\ue655",
    "Window Minimise": "\ue654",
    "Window Restore": "\ue656",
    "Window Snipping": "\uf7ed",
    "Windows Insider": "\uf1ad",
    Wire: "\ue95f",
    "Wired USB": "\uecf0",
    "Wireless USB": "\uecf1",
    "Work Account": "\ue631",
    "Work Solid": "\ueb4e",
    Work: "\ue821",
    World: "\ue909",
    "Xbox One Console": "\ue990",
    "Zero Bars": "\ue904",
    "Zip Folder": "\uf012",
    "Zoom In": "\ue8a3",
    "Zoom Mode": "\uece8",
    "Zoom Out": "\ue71f",
    Zoom: "\ue71e",
} as const;

export default Icons;
